// tests/next-action-state.version.test.js — split from next-action-state.test.js (E3, v0.2.267).
// Slice: no-stale-version guard (tracks live config VERSION + CURRENT_TEST_STATUS).
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  NEXT_ACTION_STATE_SCHEMA, buildNextActionState,
} from '../tools/nextActionState.mjs';
import { VERSION } from '../src/config.js';
import { CURRENT_TEST_STATUS } from '../src/engine/dashboard/toriiQuestDashboardData.js';
import { handoff } from './_next-action-state-helpers.js';

// No-stale-version guard: the next-action state must track the live config VERSION, and the
// curated test count it carries must match CURRENT_TEST_STATUS — so a version/test bump can't
// leave this artifact behind.
describe('next-action-state — no stale version', () => {
  it('reports the current config VERSION when fed it (no hardcoded stale version)', () => {
    const s = buildNextActionState({ agentHandoff: handoff({ version: VERSION, packageVersion: VERSION.replace(/^v/, '') }) });
    expect(s.version).toBe(VERSION);
  });

  it('the committed NEXT_ACTION_STATE.json (if present) is not stale vs config VERSION', () => {
    let raw = null;
    try { raw = readFileSync(join(process.cwd(), 'NEXT_ACTION_STATE.json'), 'utf8'); } catch { raw = null; }
    if (raw == null) return; // artifact regenerated by the build; absence is not a failure here
    const parsed = JSON.parse(raw);
    expect(parsed.schema).toBe(NEXT_ACTION_STATE_SCHEMA);
    expect(parsed.version).toBe(VERSION);
    expect(parsed.tests).toEqual({ passing: CURRENT_TEST_STATUS.passing, files: CURRENT_TEST_STATUS.files });
  });
});
