// tools/csp.mjs — single source of truth for the Content-Security-Policy (S3, v0.2.266).
//
// The CSP ships as an HTTP RESPONSE HEADER, never a <meta> tag. It is emitted in three
// places, all derived from CSP_VALUE here so they cannot drift:
//   1. dist/_headers  — written at build by the vite plugin; honoured by the static host
//      (S3 / torii-quest.pplx.app, Netlify/Cloudflare-style `_headers`).
//   2. the Vite preview server (production-parity local serving).
//   3. the Caddy / Nginx server blocks documented in VPS_INSTALL.md (VPS deploy path).
//
// script-src uses `strict-dynamic` + a sha256 hash of the SINGLE trusted classic inline
// bootstrap script. At build the vite plugin removes the static entry <script> tag and
// has that bootstrap script `import('/assets/torii-entry.js')` instead; `strict-dynamic`
// then propagates trust to the entry and every lazily-imported chunk (three-vendor,
// rapier, arenaRuntime, …) without listing any of them. `'self'`/`blob:` are kept as a
// CSP-Level-2 fallback for browsers that don't understand `strict-dynamic` (they ignore
// `strict-dynamic` and load the same-origin entry via `'self'`).
//
// connect-src carries the Nostr relay sockets plus the ONE read-only HTTPS origin the
// update-check needs — https://api.github.com (releases/latest, GET only, cached client-side
// in liveUpdateCheck.js). No script/style/font third-party origin appears anywhere: gstatic.com
// is gone (S4) because the Draco decoder is vendored at /draco/ and fetched same-origin.

// sha256 of the built inline bootstrap script. This is a FALLBACK used only by the
// `vite preview` server when no built dist/index.html exists yet. The ACTUAL sha for a
// shipped build is computed at build time from the emitted inline script (which now
// carries a per-build cache-bust query on the entry import — see vite.config.js) and is
// written into dist/_headers by the plugin. regression-check verifies that dist/_headers
// carries the sha recomputed from dist/index.html (self-consistency), so a stale or
// mismatched sha can't slip past the policy.
export const INLINE_SCRIPT_SHA256 = "sha256-434PYYX1c2Tr6+CPmiAm+CckYnPDnRO31MIet6VpKv4=";

export const CSP_DIRECTIVES = [
  ["object-src", "'none'"],
  ["base-uri", "'self'"],
  ["form-action", "'self'"],
  ["script-src", `'self' 'wasm-unsafe-eval' blob: 'strict-dynamic' ${INLINE_SCRIPT_SHA256}`],
  ["worker-src", "'self' blob:"],
  ["connect-src", "'self' blob: https://api.github.com wss://relay.damus.io wss://nos.lol wss://relay.nostr.band wss://relay.primal.net"],
];

export const CSP_VALUE = CSP_DIRECTIVES.map(([k, v]) => `${k} ${v}`).join("; ");

// The exact dynamic-import line the build plugin appends to the trusted inline bootstrap.
// v0.2.283: a per-build cache-bust query is appended so Cloudflare's edge cache (4h)
// can never serve a stale entry that points at a dead/old chunk hash after a publish.
// The query is filled in by the plugin at build time; this constant is the dev fallback.
export const ENTRY_IMPORT_LINE = "  import('/assets/torii-entry.js');";

// Build a CSP value whose script-src carries the GIVEN inline-script sha (used at build
// time so the emitted _headers always matches the actual emitted inline bootstrap).
export function cspValueForSha(inlineSha) {
  const dirs = CSP_DIRECTIVES.map(([k, v]) =>
    k === 'script-src'
      ? [k, `'self' 'wasm-unsafe-eval' blob: 'strict-dynamic' ${inlineSha}`]
      : [k, v],
  );
  return dirs.map(([k, v]) => `${k} ${v}`).join("; ");
}

// Static-host `_headers` file body carrying the CSP for the GIVEN inline-script sha.
export function headersFileBodyForSha(inlineSha) {
  return `# Generated by the vite CSP plugin (tools/csp.mjs) — do not edit by hand.\n/*\n  Content-Security-Policy: ${cspValueForSha(inlineSha)}\n`;
}

// Static-host `_headers` file body (applies the CSP to every path). Legacy fallback
// using the hardcoded INLINE_SCRIPT_SHA256; the build plugin uses headersFileBodyForSha()
// with the sha it recomputes from the emitted inline script.
export function headersFileBody() {
  return headersFileBodyForSha(INLINE_SCRIPT_SHA256);
}
