// tools/csp.mjs — single source of truth for the Content-Security-Policy (S3, v0.2.266).
//
// The CSP ships as an HTTP RESPONSE HEADER, never a <meta> tag. It is emitted in three
// places, all derived from CSP_VALUE here so they cannot drift:
//   1. dist/_headers  — written at build by the vite plugin; honoured by the static host
//      (S3 / torii-quest.pplx.app, Netlify/Cloudflare-style `_headers`).
//   2. the Vite preview server (production-parity local serving).
//   3. the Caddy / Nginx server blocks documented in VPS_INSTALL.md (VPS deploy path).
//
// script-src uses `strict-dynamic` + a sha256 hash of the SINGLE trusted classic inline
// bootstrap script. At build the vite plugin removes the static entry <script> tag and
// has that bootstrap script `import('/assets/torii-entry.js')` instead; `strict-dynamic`
// then propagates trust to the entry and every lazily-imported chunk (three-vendor,
// rapier, arenaRuntime, …) without listing any of them. `'self'`/`blob:` are kept as a
// CSP-Level-2 fallback for browsers that don't understand `strict-dynamic` (they ignore
// `strict-dynamic` and load the same-origin entry via `'self'`).
//
// No third-party origin appears anywhere: gstatic.com is gone (S4) because the Draco
// decoder is vendored at /draco/ and fetched same-origin (covered by connect-src 'self').

// sha256 of the built inline bootstrap script (the one classic inline <script> in the
// emitted dist/index.html, AFTER the plugin appends the entry import). Deterministic:
// the entry filename is pinned (assets/torii-entry.js) and the injected line is fixed.
// regression-check recomputes this from dist/index.html and FAILS on any mismatch, so a
// changed inline script can't slip past the policy.
export const INLINE_SCRIPT_SHA256 = "sha256-434PYYX1c2Tr6+CPmiAm+CckYnPDnRO31MIet6VpKv4=";

export const CSP_DIRECTIVES = [
  ["object-src", "'none'"],
  ["base-uri", "'self'"],
  ["form-action", "'self'"],
  ["script-src", `'self' 'wasm-unsafe-eval' blob: 'strict-dynamic' ${INLINE_SCRIPT_SHA256}`],
  ["worker-src", "'self' blob:"],
  ["connect-src", "'self' blob: wss://relay.damus.io wss://nos.lol wss://relay.nostr.band wss://relay.primal.net"],
];

export const CSP_VALUE = CSP_DIRECTIVES.map(([k, v]) => `${k} ${v}`).join("; ");

// The exact dynamic-import line the build plugin appends to the trusted inline bootstrap.
export const ENTRY_IMPORT_LINE = "  import('/assets/torii-entry.js');";

// Static-host `_headers` file body (applies the CSP to every path).
export function headersFileBody() {
  return `# Generated by the vite CSP plugin (tools/csp.mjs) — do not edit by hand.\n/*\n  Content-Security-Policy: ${CSP_VALUE}\n`;
}
